version: '3.8'

services:
  varta-mqtt-service:
    image: ghcr.io/marscerbl/vartal_pulse_neo_to_mqtt:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
    container_name: varta-mqtt-service